Plugin to map feature
codebase-berkeley/telegraf pull request #20
Opened 2020-12-06 22:23 UTC by wangztim

**Description of changes**

Added functionality to convert a plugin's struct to a map with reflection instead of json.(un)marshal

2020-12-06 22:30 UTC, TheGoldenKyle requested changes

2020-12-06 22:30 UTC, TheGoldenKyle commented on agent/agent.go
> +
No space here (go convention)

2020-12-06 22:30 UTC, TheGoldenKyle commented on agent/agent.go
> +func (a *Agent) CreateInput(name string) (interface{}, error) {
Why are we returning an ```interface{}``` for both of these? Also what are these creating? It just seems like it's running a plugin?

2020-12-06 22:39 UTC, jodielu requested changes

2020-12-06 22:39 UTC, jodielu commented on agent/agent.go
> +func (a *Agent) CreateInput(name string) (interface{}, error) {
Add comment for all exported functions (go convention)

2020-12-06 22:39 UTC, jodielu commented on agent/agent.go
> +func (a *Agent) CreateOutput(name string) (interface{}, error) {
Add comment for all exported functions (go convention)

2020-12-06 22:39 UTC, jodielu commented on assistant/assistant.go
> +	case "AGGREGATOR":
Delete this case

2020-12-06 22:39 UTC, jodielu commented on assistant/assistant.go
> +	case "PROCESSOR":
Delete this case

2020-12-06 22:39 UTC, jodielu commented on assistant/assistant_test.go
> +	// 	d, _ := json.Marshal(s.Defaults)
Why is this commented out?

2020-12-06 22:47 UTC, jodielu commented on assistant/assistant.go
> +		defaultValues, err = assistant.agent.GetDefaultOutputPlugin(req.Plugin.Name)
Are these plugin variables used anywhere else? Why do we need to create these plugin objects

2020-12-06 23:27 UTC, jodielu commented on agent/agent.go
> +			a.StopOutputPlugin(name)
Should this have a second parameter: true?

2020-12-06 23:27 UTC, jodielu commented on agent/agent.go
> +// ? Should we make the nil check a parameter?
Remove this comment - the function seems fine as is

2020-12-07 20:58 UTC, wangztim commented
Merge?

2020-12-07 22:11 UTC, merged