Dev/epic2
codebase-berkeley/telegraf pull request #3
Opened 2020-10-08 04:08 UTC by nikhilJain17

Epic 2 work:
- Data sources functions
- Adding plugins

2020-10-08 06:07 UTC, TheGoldenKyle requested changes

2020-10-08 06:07 UTC, TheGoldenKyle commented on agent/agent.go
> +func PrintAgentInputPlugins(a *Agent) {
Instead of just printing the plugins, why not have the function return an array of their names?

2020-10-08 06:07 UTC, TheGoldenKyle commented on agent/agent.go
> +func PrintAgentOutputPlugins(a *Agent) {
Why do the functions take in an agent as an argument rather than being a method of the agent class?
`func (a *Agent) PrintAgentOutputPlugins()`
Then you could call it like `a.PrintAgentOutputPlugins`

2020-10-08 06:07 UTC, TheGoldenKyle commented on agent/agent.go
> +func PrintAgentInputPlugins(a *Agent) {
How about a generic ```GetPlugins``` method of an agent that takes in which type of plugins you want?
eg: `func (a *Agent) GetPlugins(type PluginType)`, with PluginType being a wrapper around strings that are either like "input" or "output" or something? They might already have something like this, not sure.

2020-10-08 06:07 UTC, TheGoldenKyle commented on agent/agent.go
> +func AddInputPluginToAgent(a *Agent, plugin_name string) {
Same comment as below. Why not make these methods of the `Agent` class?

2020-10-08 06:07 UTC, TheGoldenKyle commented on cmd/telegraf/telegraf.go
> +	log.Printf("I! Loading Inputs: %s", strings.Join(c.InputNames(), " "))
Why?

2020-10-08 06:07 UTC, TheGoldenKyle commented on telegraf.conf
> +# Telegraf Configuration
Don't commit things that are unique to a particular dev or environment, like this config.

2020-10-08 06:07 UTC, TheGoldenKyle commented on agent/agent.go
> +	"github.com/influxdata/telegraf/plugins/inputs"
Make sure you follow golang convention.
See "Formatting Imports" on https://www.digitalocean.com/community/tutorials/importing-packages-in-go
Golang has a lot of tools that do formatting and linting and things like that for you, such as `govet`, `golint` and `goimports`.

2020-10-08 06:10 UTC, TheGoldenKyle commented
Also, try to make sure the commits follow good convention. 

All these commits could be squashed down into one with a commit message like "Add functionality to get available Agent plugins" or something

2020-10-08 06:13 UTC, TheGoldenKyle requested changes

2020-10-08 06:13 UTC, TheGoldenKyle commented on agent/agent.go
> +func PrintAgentInputPlugins(a *Agent) {
Also, what's the purpose of these two PrintAgentXXXPlugins functions? They seem to just print the currently running ones. Were they used to test which plugins were currently in the Config?

2020-10-08 21:38 UTC, surbhiijain commented
#1

2020-10-13 22:20 UTC, sjwang90 commented
Link to InfluxData Repo: influxdata/idpe#6281

2020-10-22 04:51 UTC, TheGoldenKyle commented
These changes are all reflected in https://github.com/codebase-berkeley/telegraf/pull/7 and will be merged with that.

2020-10-22 04:51 UTC, closed without merging